import { NextRequest, NextResponse } from "next/server";
import { createClient } from "@supabase/supabase-js";

function getAdminClient() {
  return createClient(
    process.env.NEXT_PUBLIC_SUPABASE_URL!,
    process.env.SUPABASE_SERVICE_ROLE_KEY!,
    { auth: { autoRefreshToken: false, persistSession: false } }
  );
}

// Must match the path shape generated by /api/dental/quote-comparison/upload-url —
// the client only ever echoes back a path it received from us, but this route is
// a separate trust boundary now that upload and lead-submit are two requests, so
// reject anything that doesn't look like our own generated path.
const STORAGE_PATH_RE = /^quote-comparisons\/\d{4}-\d{2}-\d{2}\/[0-9a-f-]{36}-[a-zA-Z0-9._-]+$/;

const BUCKET = "dental-quotes";

// The client only ever tells us a path string — never trust that the object
// behind it actually landed in Storage. list() with a search filter avoids
// downloading the file just to confirm it exists.
async function storageObjectExists(
  supabase: ReturnType<typeof getAdminClient>,
  storagePath: string
): Promise<boolean> {
  const lastSlash = storagePath.lastIndexOf("/");
  const dir = storagePath.slice(0, lastSlash);
  const fileName = storagePath.slice(lastSlash + 1);

  const { data, error } = await supabase.storage
    .from(BUCKET)
    .list(dir, { search: fileName, limit: 1 });

  if (error) {
    console.error("[quote-comparison] storage existence check failed:", error);
    return false;
  }
  return (data ?? []).some((entry) => entry.name === fileName);
}

type Payload = {
  patient_name?: string;
  patient_phone?: string;
  storage_path?: string;
  original_file_name?: string;
  original_file_mime_type?: string;
  original_file_size?: number;
  consent?: boolean;
  utm_source?: string;
  utm_medium?: string;
  utm_campaign?: string;
  utm_content?: string;
  utm_term?: string;
  fbclid?: string;
  landing_path?: string;
  referrer?: string;
};

// The file is already sitting in Storage by the time this fires (uploaded
// directly from the browser via a signed upload URL — see
// /api/dental/quote-comparison/upload-url). This route only ever receives a
// small JSON body: name, WhatsApp, a pointer to the uploaded file, and
// attribution. It never touches file bytes.
export async function POST(req: NextRequest) {
  let body: Payload;
  try {
    body = await req.json();
  } catch (e) {
    console.error("[quote-comparison] json parse error:", e);
    return NextResponse.json(
      { error: "No se pudo leer la solicitud. Intenta nuevamente.", step: "parse" },
      { status: 400 }
    );
  }

  const patientName = body.patient_name?.trim();
  const phone        = body.patient_phone?.trim();
  const storagePath  = body.storage_path?.trim();

  if (!patientName || patientName.length < 3) {
    return NextResponse.json({ error: "Nombre y apellido requeridos", step: "validate" }, { status: 400 });
  }
  if (!phone) {
    return NextResponse.json({ error: "Falta WhatsApp", step: "validate" }, { status: 400 });
  }
  if (!storagePath || !STORAGE_PATH_RE.test(storagePath)) {
    return NextResponse.json({ error: "Falta archivo", step: "validate" }, { status: 400 });
  }
  if (!body.consent) {
    return NextResponse.json(
      { error: "Debes aceptar los términos para continuar", step: "validate" },
      { status: 400 }
    );
  }

  const supabase = getAdminClient();

  const fileExists = await storageObjectExists(supabase, storagePath);
  if (!fileExists) {
    console.error(`[quote-comparison] file_not_found for storage_path=${storagePath}`);
    return NextResponse.json(
      { error: "No pudimos confirmar tu archivo subido. Vuelve a intentar la subida.", step: "file_missing" },
      { status: 400 }
    );
  }

  const { data: record, error: insertError } = await supabase
    .from("dental_quote_requests")
    .insert({
      patient_name:            patientName,
      patient_phone:           phone,
      storage_path:            storagePath,
      original_file_name:      body.original_file_name ?? null,
      original_file_mime_type: body.original_file_mime_type ?? null,
      original_file_size:      body.original_file_size ?? null,
      source:                  "quote_comparison",
      status:                  "submitted",
      utm_source:              body.utm_source ?? null,
      utm_medium:              body.utm_medium ?? null,
      utm_campaign:            body.utm_campaign ?? null,
      utm_content:             body.utm_content ?? null,
      utm_term:                body.utm_term ?? null,
      fbclid:                  body.fbclid ?? null,
      landing_path:            body.landing_path ?? null,
      referrer:                body.referrer ?? null,
    })
    .select("id")
    .single();

  if (insertError || !record) {
    console.error("[quote-comparison] database_insert_failed:", insertError);

    // Best-effort cleanup of the orphaned file — only the exact, already-validated
    // path, never anything client-supplied beyond what we just confirmed exists.
    const { error: cleanupError } = await supabase.storage.from(BUCKET).remove([storagePath]);
    if (cleanupError) {
      console.error("[quote-comparison] orphan_cleanup_failed for storage_path:", storagePath, cleanupError.message);
    }

    return NextResponse.json(
      { error: "Error guardando tu solicitud. Intenta nuevamente.", step: "database" },
      { status: 500 }
    );
  }

  console.log(`[quote-comparison] record saved — id=${record.id}`);
  return NextResponse.json({ success: true, quote_request_id: record.id });
}
